version: '3'

services:
  service-name:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        tag: textract
    image: textract:latest
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ~/.aws/:/root/.aws:ro